/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Card: typeof import('./components/card.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    ReservationCard: typeof import('./components/ReservationCard.vue')['default']
    ReservationCardImproved: typeof import('./components/reservation-card-improved.vue')['default']
    ReservationCardSvgApproach: typeof import('./components/reservation-card-svg-approach.vue')['default']
    ReservationCardUpdate: typeof import('./components/reservation-card-update.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
